import { listClinicalAssistsForIntake } from "@/server/db";
import { fmtDate } from "../lib/format";
import { SupersedeForm } from "./SupersedeForm";

/**
 * Renders all clinical_assists for an intake — Dr Kyana sees the AI-drafted
 * differential (and any future kinds) with the persisted disclaimer, the
 * provenance footer, and either the existing supersede note or a control to
 * add one.
 *
 * Server component — reads directly from D1 on each render (the page is
 * already `dynamic = 'force-dynamic'`). If no assists exist for the intake,
 * the panel renders nothing at all (no empty-state noise).
 */
export async function ClinicalAssistsPanel({
  intakeId,
}: {
  intakeId: string;
}) {
  const assists = await listClinicalAssistsForIntake(intakeId);
  if (assists.length === 0) return null;

  return (
    <section className="card border-rose-200/60 bg-rose-50/30">
      <h2 className="mb-1 text-sm font-semibold">Clinical assists (AI-drafted)</h2>
      <p className="mb-3 text-xs text-muted">
        Generated by the agent on your request. Not a diagnosis — review and
        supersede with your own clinical assessment when you see the patient.
      </p>
      <ul className="space-y-4">
        {assists.map((a) => (
          <li
            key={a.id}
            className="rounded-lg bg-white p-3 ring-1 ring-ink/5"
          >
            {a.disclaimer_persisted && (
              <p className="mb-2 rounded bg-amber-100/60 px-2 py-1 text-[11px] font-medium text-amber-900">
                AI-assisted reasoning — not a diagnosis. For clinical review by
                Dr Kyana.
              </p>
            )}
            <pre className="whitespace-pre-wrap font-sans text-sm leading-relaxed text-ink">
              {a.output_markdown}
            </pre>
            {a.citations.length > 0 && (
              <details className="mt-2 text-xs text-muted">
                <summary className="cursor-pointer">
                  Citations ({a.citations.length})
                </summary>
                <ol className="ml-5 mt-1 list-decimal space-y-1">
                  {a.citations.map((c, i) => (
                    <li key={`${a.id}-cite-${i}`}>
                      <span className="font-medium text-ink">{c.title}</span>
                      {c.snippet ? <> — {c.snippet}</> : null}
                    </li>
                  ))}
                </ol>
              </details>
            )}
            <p className="mt-2 text-[11px] text-muted">
              {a.kind} · {a.model_id} · prompt {a.prompt_hash.slice(0, 8)} ·
              initiated by {a.initiated_by} · {fmtDate(a.created_at)}
            </p>
            {a.superseded_by_clinician_note ? (
              <div className="mt-3 rounded border-l-4 border-emerald-400 bg-emerald-50/60 p-2">
                <p className="text-xs font-medium text-emerald-900">
                  Superseded by {a.superseded_by ?? "Dr Kyana"} on{" "}
                  {fmtDate(a.superseded_at)}
                </p>
                <p className="mt-1 whitespace-pre-wrap text-sm text-ink">
                  {a.superseded_by_clinician_note}
                </p>
              </div>
            ) : (
              <SupersedeForm assistId={a.id} />
            )}
          </li>
        ))}
      </ul>
    </section>
  );
}
